
include:
  - board: ergodash_mini_left
    snippet: studio-rpc-usb-uart
  - board: ergodash_mini_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: ergodash_mini_dongle dongle_display
    artifact-name: ergodash_mini_dongle
